"""add_data_conflicts_and_uncertainty_notes

Revision ID: 599fd346e439
Revises: 0fe2c1f3fd26
Create Date: 2026-09-29 11:06:50.470951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '599fd346e439'
down_revision: Union[str, Sequence[str], None] = '0fe2c1f3fd26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_research', sa.Column('data_conflicts', sa.JSON(), nullable=True))
    op.add_column('company_research', sa.Column('uncertainty_notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company_research', 'uncertainty_notes')
    op.drop_column('company_research', 'data_conflicts')
    # ### end Alembic commands ###
